---
- hosts: [grafana, prometheus] 
  connection: ssh
  remote_user: centos
  become: true
  vars:
        packages:
          - epel-release
          - vim
          - wget
          - net-tools
          - curl
  tasks:
        - name: Installing Packages
          yum:
            name: "{{ packages }}"
            state: present
 #         with_items: 
  #          - "{{ packages }}"
