---
- hosts: jenkins
  remote_user: centos
  connection: ssh
  become: true
  vars:
    packages:
        - epel-release
        - vim
        - wget
        - curl
        - net-tools
        - java-1.8.0-openjdk
        - git
  tasks:
        - name: Installing Packages
          yum:
            name: "{{ item }}"
          with_items: "{{ packages }}"
        
        - name: Adding jenkins repo
          command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
        
        - command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

        - name: installing jenkins
          yum:
            name: jenkins-2.89.4
            state: present
        
        - name: Starting jenkins service
          service:
            name: jenkins
            state: started
            enabled: yes

